config/routes.rb
Rails.application.routes.draw do
  resources :home, only: %i[index]
  resources :users, only: %i[new create show]
  resources :groups
  resources :routines

  get '/log_in', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  delete '/sessions', to: 'sessions#destroy'
  root 'home#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bridge.rb
class Bridge < ApplicationRecord
  belongs_to :routine
  belongs_to :group
end

app/models/group.rb
# rubocop:disable Layout/LineLength
class Group < ApplicationRecord
  has_one_attached :icon

  validates :name, presence: true, uniqueness: true, format: { with: /\A[a-zA-Z\s]+\z/, message: 'Only letters are allowed' }, length: { in: 3..30 }

  has_many :bridges
  has_many :routines, through: :bridges
end
# rubocop:enable Layout/LineLength

app/models/routine.rb
class Routine < ApplicationRecord
  validates :hours, presence: true, numericality: { only_float: true }
  validates :name, presence: true

  belongs_to :user
  has_many :bridges
  has_many :groups, through: :bridges, dependent: :destroy

  def group=(group)
    g = Group.find_by(name: group)
    groups << g if g
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true,
                   format: { with: /\A[a-zA-Z\s]+\z/, message: 'Only letters are allowed' }, length: { in: 3..30 }

  has_many :routines, foreign_key: :user_id, dependent: :destroy
  has_many :groups, through: :routines
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    User.find_by(name: session[:name]) if session[:name]
  end

  helper_method :current_user

  def require_signin
    redirect_to log_in_path, alert: 'You have to sign in first' unless current_user
  end

  def already_signin
    redirect_to groups_path, alert: 'Yoy are already logged in.' if current_user
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :require_signin

  def index
    @group = Group.all
    @routine = Routine.all
    @user = User.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to groups_path, notice: 'Group sucessfully created'
    else
      render :new, notice: @group.errors.full_messages
    end
  end

  def show
    @group = Group.find(params[:id])
    @routine = Routine.find(params[:id]) unless @routine.nil?
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    flash.notice = "Group '#{@group.name}' was Deleted!"

    redirect_to groups_path
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    @group.update(group_params)

    flash.notice = "Group '#{@group.name}' was Updated!"

    redirect_to group_path(@group)
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :already_signin
  def index; end
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  before_action :require_signin

  def index
    @group = Group.all
    @routine = Routine.all
    @user = User.all
  end

  def new
    @routine = Routine.new
  end

  def create
    @routine = Routine.create(routine_params)
    @routine.group = params[:group_ids]

    if @routine.save
      redirect_to groups_path, notice: 'Your activity was loged!, keep working hard!'
    else
      redirect_to groups_path, notice: @routine.errors.full_messages
    end
  end

  def show
    @group = Group.all
    @routine = Routine.all
  end

  def destroy
    @routine = Routine.find(params[:id])
    @routine.destroy

    flash.notice = "Routine '#{@routine.name}' was Deleted!"

    redirect_to groups_path
  end

  def edit
    @routine = Routine.find(params[:id])
  end

  def update
    @routine = Routine.find(params[:id])
    @routine.update(routine_params)

    flash.notice = "Routine '#{@routine.name}' was Updated!"

    redirect_to user_path(current_user)
  end

  private

  def routine_params
    params.require(:routine).permit(:name, :hours, :user_id, :group_ids)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(name: params[:name])
    if @user.nil?
      flash.now[:alert] = 'User must exist.'
      render :new
    else
      session[:name] = @user.name
      redirect_to groups_path, notice: "Welcome back #{@user.name}"
    end
  end

  def destroy
    session[:name] = nil
    redirect_to root_url, notice: 'See you soon'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:name] = @user.name
      redirect_to groups_path, notice: 'Welcome to the party!'
    else
      redirect_to new_user_path, notice: @user.errors.full_messages
    end
  end

  def show
    @groups = Group.all
    @user = User.find_by(id: params[:id])
    @routine = Routine.all
  end

  private

  def user_params
    params.require(:user).permit(:name, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    if current_user.nil?
      (link_to 'Log In', log_in_path, class: 'home_button').html_safe +
        (link_to 'Sign Up', new_user_path, class: 'home_button').html_safe
    else
      avatar(current_user) +
        (link_to "#{current_user.name} Activities", user_path(current_user),
                 class: 'home_button').html_safe + (link_to 'External Activities', routines_path,
                                                            class: 'home_button').html_safe +
        (link_to 'Groups', groups_path, class: 'home_button').html_safe +
        (link_to 'Log Out', sessions_path, method: :delete, class: 'home_button').html_safe
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def routine_check(arg)
    if arg.routines.where(user_id: current_user.id).last.nil?
      render 'noroutine'
    else
      routine_name(arg)
    end
  end

  # rubocop: disable Style/GuardClause
  def routine_name(arg)
    if arg.routines.last.nil?
      "<p>Your Last Activity</p><br/>#{arg.routines.where(user_id: current_user.id).last.name} <br>".html_safe
    end
  end
  # rubocop: enable Style/GuardClause

  def icon(arg)
    if arg.icon.attached?
      (image_tag arg.icon.variant(resize_to_limit: [200, 200]), class: 'item_icon').html_safe
    else
      (image_tag 'https://placeimg.com/200/200/tech', class: 'item_icon').html_safe
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/routines_helper.rb
module RoutinesHelper
  def user_check(routine)
    routine.user.name.html_safe if routine.groups.empty?
  end

  def name_check(routine)
    routine.name.html_safe if routine.groups.empty?
  end

  def time_check(routine)
    routine.hours.to_s.html_safe if routine.groups.empty?
  end

  def group_name(routine)
    if routine.groups.last.nil?
      'External'
    else
      routine.groups.last.name
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
# rubocop:disable Layout/LineLength
module UsersHelper
  def total_hours_group
    sum = 0
    @group.routines.each do |f|
      sum += f.hours
    end
    sum
  end

  def total_hours_user
    sum = 0
    @user.routines.each do |f|
      sum += f.hours
    end
    sum
  end

  def total_hours_each(arg)
    sum = 0
    arg.routines.each do |f|
      sum += f.hours if f.user_id == current_user.id
    end
    sum
  end

  def external_group(arg)
    if arg.groups.empty?
      'External'
    else
      arg.groups.last.name
    end
  end

  def avatar(arg)
    if arg.avatar.attached?
      ((image_tag current_user.avatar.variant(resize_to_limit: [100, 100]))).html_safe
    else
      (image_tag 'http://2.bp.blogspot.com/-BVgTOe82aaI/VZln4Ny-LPI/AAAAAAAAA6Y/hKchnruxKtg/s1600/2000px-User_icon_2.svg.png', size: '200x200').html_safe
    end
  end
end
# rubocop:enable Layout/LineLength

app/views/groups/_form.html.erb
  <%=form_with(model:@group,local:true) do |f|%>
  <div class="input_container">
    <%= f.object.errors.full_messages.join(", ") if f.object.errors.any? %>
    <%=f.text_field :name,required:true,autofocus:true,placeholder:"Name of the group",class:"input_area"%>
    <%= f.file_field :icon %>
    <%=f.submit "Save",class:"input_button"%>
  <%end%>

</div>

<%= link_to 'Back To Groups', groups_path, class:'create_button', id:'return' %>

app/views/groups/_noroutine.html.erb
<p>You haven't track</p>
<p>Anything in this group.</p>

app/views/groups/_routines.html.erb
  <%= form_for @routine.build do |f| %>        
    <div class="routine_box">
      <%= f.hidden_field :user_id, value: current_user.id %> 
      <%= f.text_field :name,class:'routine_text',placeholder:'What did you do?' %>
      <%= f.number_field :hours, class:'routine_text',placeholder:'For how long?' %>
      <%= f.collection_select(:group_ids, Group.all, :id, :name,:include_blank => 'None')%>
      <%= f.submit "Log an Activity", class: "routine_button" %>
    </div>
  <% end %>

app/views/groups/edit.html.erb
<h1 class="title_two">Change the group Information</h1>

<%= render 'form' %>

app/views/groups/index.html.erb
<h1 class="title_two" id="top_title"> Available Groups </h1>
<div class='information_area'>
  <%= link_to 'Create New Group', new_group_path, class:'create_button', id:'option_link' %>
  <div class="items_area">
    <%@group.each do |g|%>
      <div class="item_container">
        <%= icon(g)%>
        <h2><%=link_to g.name, group_path(g)%></h2>
        <div class="item_info"> 
          <%= link_to group_path(g) do%>
            <p><%= routine_check(g)%></p>
            <p>Group Created at <%=g.created_at.to_date%></p> </p>        
          <%end%>
      </div>        
    </div>
  <%end%>  
</div>    
   
  <h2 class="title_two">Track an Activity</h2>

  <%= render 'routines' %>

app/views/groups/new.html.erb
<h1 class="title_two">Create a New Group</h1>

<%= render 'form' %>

app/views/groups/show.html.erb
<div class="information_area">
  <div class="items_area">
    <div class="item_container" id="item_show">   
      <%= icon(@group)%>
      <h1 class="item_tittle"><%= @group.name %></h1>
      <p class="item_text"> Total Hours</p>
      <p class="item_text"><%= total_hours_group %></p>
    </div>
  </div>
  <%= link_to 'Edit', edit_group_path(@group), class: 'create_button' , id:'edit_button'%>      
  <div class="item_container" id="smallHourContainer">
    <p class="item_text"> Total Hours</p>
    <p class="item_text"><%= total_hours_group %></p>
  </div>
  <div class="user_routines">
    <div class="routine_container_one">
      <p>User</p>
      <p>Activity</p>
      <p>Hours</p>
    </div>

    <div class="routine_container">

      <% @group.routines.reverse.each do |f|%>
          <p class="routine_item"><%= f.user.name%></p>
          <p class="routine_item"><%= f.name%></p>
          <p class="routine_item"><%= f.hours%></p>
      <%end%>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="information_area">
<div class="title">
  <h1 class="home_tittle">ACTIVITY TRACKER</h1>
  <h2>A tool to keep track of the time you spend.</h2>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Activity Tracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css" %>
    <meta name="description" content="Activity Tracker" />
    <meta name="title" property="og:title" content="Activiy Tracker" />
    <meta property="og:type" content="Rails App" />
    <meta name="image" property="og:image" content="https://live.staticflickr.com/65535/51100083991_330be08348.jpg" />
    <meta name="description" property="og:description" content="_" /><meta name="author" content="This project is a simple app built using basic Ruby on Rails functionalities in this app you can create an account, and when logged in, you will be able to  build groups and routines and keep track of them." />
  </head>

  <body>  
  <%=render "shared/errors" %>
  <nav class="ham">
  <label for="hamburger">&#9776;</label>
  <input type="checkbox" id="hamburger"/>
      <div class="home_container">
        <%= logged_in?%>
      </div>
  </nav>

    <%= yield %>
  </body>
</html>

app/views/routines/_routines.html.erb
  <%= form_for @routine do |f| %>
    <div class="routine_box">
      <%= f.hidden_field :user_id, value: current_user.id %> 
      <%= f.text_field :name,class:'routine_text',placeholder:'What did you do?' %>
      <%= f.number_field :hours, class:'routine_text',placeholder:'For how long?' %>
      <%= f.collection_select(:group_ids, Group.all, :id, :name,:include_blank => 'None')%>
      <%= f.submit "Log an Activity", class: "routine_button" %>
    </div>
  <% end %>

app/views/routines/edit.html.erb
<h1 class="title_two", id='top_title'>Edit Activity</h1>

<%= render 'routines' %>

app/views/routines/index.html.erb
<h2 class="title_two" id="top_title">External Routines</h2>

<div class="information_area">
  <div class="user_routines">
    <div class="routine_container_one">
      <p>User</p>
      <p>Activity</p>
      <p>Hours</p>
    </div>

    <div class="routine_container">

      <% @routine.reverse.each do |f|%>    
        <p><%= user_check(f)%></p>
        <p><%= name_check(f)%></p>
        <p><%= time_check(f)%></p>
      <%end%>
    </div>
  </div>
</div>

app/views/shared/_errors.erb
<% flash.each do |type, msg| %>
  <div class="alert" role="alert">
    <%= msg %>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="information_area">
  <h2 class="title_two">Register</h2>
  <%=form_with(model:@user,local:true) do |f|%>
    <div class="input_container">
      <%=f.text_field :name,autofocus:true,placeholder:"Your name here",class:'input_area' %>
      <%= f.file_field :avatar %>
      <%=f.submit "Sign Up", class:'input_button'%>
    </div>
  <%end%>
</div>

app/views/users/show.html.erb
<div class="information_area">
  <div class="user_info_area">
    <div class="user_container" >
      <h1 class=""> <%= current_user.name %> </h1>
      <p>Total time spend in all activities.</p>
      <p><%= total_hours_user %></p>
    </div>
    <div class="user_container" >

      <% @groups.each do |g| %>
      <% if g.routines.find_by(user_id: current_user.id) && g.id != 1%>
        <p class="group_name"> Total time Spend <%= g.name %> </p>
          <%= total_hours_each(g) %>
        <%end%>    
      <%end%>
    </div>
  </div>
  <div class="user_routines" id='user_show'>
    <div class="routine_container_one">
      <p>Group</p>
      <p>Activity</p>
      <p>Hours</p>
      <p>Options</p>
    </div>
    <div class="routine_container" id='user_view_routines'>
      <% @user.routines.reverse.each do |f|%>
        <p class="routine_item"><%= external_group(f)%></p>
        <p class="routine_item"><%= f.name%></p>
        <p class="routine_item"><%= f.hours%></p>
        <div class="routine_item" id='routine_options'>
          <%= link_to 'Edit', edit_routine_path(f), class: 'routine_link'%>
          <%= link_to 'Delete', routine_path(f),class: 'routine_link', method: :delete, data: {confirm: "Are you sure about deleting the activity?"} %> &nbsp;
        </div>    
      <%end%>
    </div>
  </div>
</div>